# -*- coding: utf-8 -*-
"""
Created on Wed Aug  9 10:34:26 2017

@author: lewismoffat

This script is statistics focused. It generates tSNE plots and general info
regarding the presence of CMV/EBV in patients

It is expected that the data is located in the directory: F:/seqs/*.cdr

"""
#==============================================================================
# Modules
#==============================================================================
import numpy as np
import matplotlib.pyplot as plt
import dataProcessing as dp
import pdb
import seaborn as sns 

from collections import defaultdict
from collections import Counter

from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
from matplotlib import pylab

#==============================================================================
# Load Data
#==============================================================================
# load in sequences and vj info for all patients with naive and beta chains
seqs, vj = dp.loadAllPatients()
# remove duplicates for ease of classification and building dictionaries later 
seqs[0], seqs[1], vj[0], vj[1], _ =dp.removeDup(seqs[0], seqs[1], vj[0], vj[0])

cmv_beta=['CASSDQSQETQYFGXG', 'CASSLTNEQFFGXG', 'CARSWAGGPRDEQYFGXG', 'CASFRGHEQFFGXG', 'CASNTGGANTDTQYFGXG', 'CASREGEYYGYTFGXG', 'CASRLGAAGSQPQHFGXG', 'CASRLGPGQPYEQYFGXG', 'CASRLGPGQPYERYFGXG', 'CASRQGAGGNQPQHFGXG', 'CASRSGPGQPYEQYFGXG', 'CASRSGTYDNSPLHFGXG', 'CASRTGAANIYEQHFGXG', 'CASRTGAANIYEQYFGXG', 'CASRVGGAGNSPLHFGXG', 'CASSAGTGIYDEAFFGXG', 'CASSAGTGIYDGAFFGXG', 'CASSARQGIDTGELFFGXG', 'CASSDPDRAVTEAFFGXG', 'CASSFGQAWETQYFGXG', 'CASSFGQAWYEQYFGXG', 'CASSLAGRETEAFFGXG', 'CASSLDRDRGRPEAFFGXG', 'CASSLGAGNYGYTFGXG', 'CASSLGGSPNYGYTFGXG', 'CASSLIGQGLGDEQFFGXG', 'CASSLMGPGQPQHFGXG', 'CASSLRPLDMNTEAFFGXG', 'CASSLRQGANAGELFFGXG', 'CASSLRQGANTGELFFGXG', 'CASSLRQGEGMGEQFFGXG', 'CASSLRQGINTGELFFGXG', 'CASSLSPSTGNYGYTFGXG', 'CASSLSTSSRNYGYTFGXG', 'CASSLVGTGGWDEQFFGXG', 'CASSPGSSFYGYPFGXG', 'CASSPLTGTGHYGYTFGXG', 'CASSPPLGSGSGDEKLFFGXG', 'CASSSHDKQGARSPLHFGXG', 'CASSSHEDRGSSSPLHFGXG', 'CASSSRDRGAYEQYFGXG', 'CASSSVNEQFFGXG', 'CASSYQTGASYGYTFGXG', 'CASSYSTGIGGGYTFGXG', 'CASTPQTGTGTYGYTFGXG', 'CASSLAPGATNEKLFFGXG', 'CASSLLQGARTEAFFGXG', 'CAISDRGGEDEQYFGXG', 'CASSFTWTSGGTTDTQYFGXG', 'CASSIPGLAGQETQYFGXG', 'CASSLDPAGQGYEQYFGXG', 'CASSLQRGRTDTQYFGXG', 'CASSSAYYGYTFGXG', 'CASSQDPGAAGYGTFGXG', 'CASSQDWGTSGNNEQFFGXG', 'CATSDRTGRHEQYFGXG', 'CASSRENSNQPQHFGXG', 'CASSIPDTEAFFGXG', 'CASSTQGSPDEQYFGXG', 'CAGSLSWGGFYNEQFFGXG', 'CASGLSDRGGDEQFFGXG', 'CASMNDGATYEQYFGXG', 'CASRALRGDNEQFFGXG', 'CASRLGLGYEQYFGXG', 'CASSCAGGPRDEQYFGXG', 'CASSLAERSYEQYFGXG', 'CASSLAPGDGYEQYFGXG', 'CASSLAWGGFYNEQFFGXG', 'CASSLGLAATYNEQFFGXG', 'CASSLGPGNYEQYFGXG', 'CASSLGSSGNEQFFGXG', 'CASSLLGLQGSYNEQFFGXG', 'CASSLRGENRDDYEQYFGXG', 'CASSLRGESLVNEQFFGXG', 'CASSLRGVSSYNEQFFGXG', 'CASSLSDRGGDEQFFGXG', 'CASSLSLLAGNNEQFFGXG', 'CASSLSWGGFYNEQFFGXG', 'CASSLSWGGFYNEQLFGXG', 'CASSLTSEQFFGXG', 'CASSPGTGREQFFGXG', 'CASSPGTLKETQYFGXG', 'CASSRRGESSYNEQFFGXG', 'CASSTSLLAGNNEQFFGXG', 'CASSVAGSATGELFFGXG', 'CASSWAGEPRDEQYFGXG', 'CASSWAGGPRDEQYFGXG', 'CASSYSTVNEQFFGXG', 'CASVNDGATYEQYFGXG', 'CATSIGSSGNEQFFGXG', 'CASSVVNEQFFGXG', 'CASSLIGVSSYNEQFFGXG', 'CASPLIEETIPYEQYFGXG', 'CASSFRGEGHPDTQYFGXG', 'CASSFYSSGRNSYFGXG', 'CASSGVGGTDTQYFGXG', 'CASSLGSSGTRQYFGXG', 'CASSLISGRARNEQFFGXG', 'CASSLKGVGQSDEQYFGXG', 'CASSSHDLAGVKSEQFFGXG', 'CASSVGAGVFTDTQYFGXG', 'CASSVGSEAYTYEQYFGXG', 'CSATGGGEQYFGXG', 'CSVGQGVVYGYTFGXG', 'CTARTGSGLAGGNEQFFGXG', 'CASKLGPAAYEQYFGXG', 'CASRVGAGNTEAFFGXG', 'CASRVGTGNLYEQYFGXG', 'CASSLSPPTYEQYFGXG', 'CASSLTSGSPYNEQFGXG', 'CASRQLPRDSLYEQYFGXG', 'CASSLQTGQETQYFGXG', 'CASSPSHGPNEKLFFGXG', 'CASSSETAPNEKLFFGXG', 'CASSSSSAPNEKLFFGXG', 'CASTTSTAPNEKLFFGXG', 'CSVEEGVLYEQYFGXG', 'CSVVSQFVTDTYFGXG', 'CASSLLPYNALVSGTDTQYFGXG', 'CASSPVGGSMAKNIQYFGXG', 'CASGRGTGTRGRNEQFFGXG', 'CASSPTSGVAGELFFGXG', 'CASSLDSQSSGNTIYFGXG', 'CASSLSGLGAAGVYEQYFGXG', 'CASSYSGNTEAFFGXG', 'CASSCQTGAACGYTFGXG', 'CASSEVTGTAWGYTFGXG', 'CASSLVTGTGKYGYTFGXG', 'CASSRTGGVDAFFGXG', 'CASSYQTGAAYGYTFGXG', 'CASSYSTGTHLEQYFGXG', 'CASSYSTGVPGELFFGXG', 'CASKGQGARDGYTFGXG', 'CASSHWDRETSGNTIYFGXG', 'CASSYGFGPAQGEKLFFGXG', 'CASIEERGSYNEQFFGXG', 'CASILERGSSYNEQFFGXG', 'CASSLESGHYEQYFGXG', 'CASSFRDRGHYEQYFGXG', 'CASSLALGVAKNIQYFGXG', 'CASSLELAMGETQYFGXG', 'CASSLGEGGAQSEQFFGXG', 'CASSLIGQGGPDTQYFGXG', 'CASSLLGQDNSPLHFGXG', 'CASSLQTGLNTEAFFGXG', 'CASSLRQGIDTGELFFGXG', 'CASSLVGEGLRDEQFFGXG', 'CASSNRDRGNYEQFFGXG', 'CASSQHDRGFSTEAFFGXG', 'CASSRELSMGETQYFGXG', 'CASSSHDRDGGYSPLHFGXG', 'CASSSHDRQGQNSPLHFGXG', 'CASSSHERQGQNSPLHFGXG', 'CASSYDWHEQFFGXG', 'CASSSKTSGVINEQFFGXG', 'CASAIVGELFFGXG', 'CASSPGLPYEQYFGXG', 'CASSSVNEQYFGXG', 'CSASNMERWVGQPQHFGXG', 'CASSNHRDRDTDTQYFGXG', 'CASSTVTSKGSDTQYFGXG', 'CSVGRAQNEQFFGXG', 'CASSPADRTRNTEAFFGXG', 'CAWSVTTSSYNSPLHFGXG', 'CAWVPGTGGTEAFFGXG', 'CASSLTGNTEAFFGXG', 'CASSYWDRITSGNTIYFGXG', 'CASSYFLAGGSGANVLTFGXG', 'CATDAGQGLFYGYTFGXG', 'CASSFRTINNEQFFGXG', 'CASSGGTGWGTGELFFGXG', 'CASSPEYLQTDTQYFGXG', 'CASSLRGGGDTQYFGXG', 'CASSALGGAGTGELFFGXG', 'CASSVPSGGETQYFGXG', 'CAPRVHTGELFFGXG', 'CASSANLAGDYNEQFFGXG', 'CASSFANYGYTFGXG', 'CASSHSRDSYNEQFFGXG', 'CASSIVNEQFFGXG', 'CASSLDVDSYNEQFFGXG', 'CASSLIGGRNGYTFGXG', 'CASSLSTAEAFFGXG', 'CASSLTGQETQYFGXG', 'CASSLVGTGGSYEQYFGXG', 'CASSPGNILYGYTFGXG', 'CASSPYGQFYEQYFGXG', 'CASSQWSNEKLFFGXG', 'CASSSAFYGYTFGXG', 'CASSSASYGYTFGXG', 'CASSSATYGYTFGXG', 'CASSSLTGTGYNEQFFGXG', 'CASSSTTGYTFGXG', 'CASSSVDEAFFGXG', 'CASSSVNEAFFGXG', 'CASSSVNGAFFGXG', 'CASSVGGPYTGELFFGXG', 'CASSVVGGRYGYTFGXG', 'CASSESMIQHFGXG', 'CASSFFSKKYNNEQFFGXG', 'CASSFWREPTYEQYFGXG', 'CASSLVGGRYGYTFGXG', 'CASSPGSINYGYTFGXG', 'CASSSAHYGYTFGXG', 'CASSSVTEAFFGXG', 'CASSSANYGYTFGXG', 'CASHYGGSSYEQYFGXG', 'CASSSLGGAGTGELFFGXG', 'CATSRDLVAETQYFGXG', 'CASSPRQGGKQPQHFGXG', 'CSARDFDRTGELFFGXG', 'CSARDPLDYVRTDTQYFGXG', 'CASNPSGGYTGELFFGXG', 'CASSFAGGAAGELFFGXG', 'CASSFGTGHTGELFFGXG', 'CASSFSGGAPGELFFGXG', 'CASSLEGFTEAFFGXG', 'CASSLEGYTEAFFGXG', 'CASSLLIQGGENTEAFFGXG', 'CASSLVSGSPTGELFFGXG', 'CASSPGTGHGELFFGXG', 'CASSRPGQGGYEQYFGXG', 'CASSWLMGTTYNEQFFGXG', 'CASTPAGGAPGELFFGXG', 'CASSFGLNQPQHFGXG', 'CASSVQGYTEAFFGXG', 'CSVDETGGGETQYFGXG', 'CSVDRYGGDTYEQYFGXG', 'CSVGGTLDTQYFGXG', 'CAWIPGTGGAGGLFGXG', 'CAWSVSDIMNTEAFFGXG', 'CASSQADRAVYGYTFGXG', 'CASSEVGATNYGYTFGXG', 'CASSYFPLADTQYFGXG', 'CANSYATGIGNYGYTFGXG', 'CASSLQTGVRSYEQYFGXG', 'CASSLTTGTGSYGYTFGXG', 'CASSPQTGAIYGYTFGXG', 'CASSPVQGAFYNSPLHFGXG', 'CASSSLYGDTGELFFGXG', 'CASSYATGIGNYGYTFGXG', 'CASSYFGGNTEAFFGXG', 'CASSYFGSQSEQYFGXG', 'CASSYQTGAIYGYTFGXG', 'CASSYQTGTIYGYTFGXG', 'CASSYSTGTPGIYTFGXG', 'CASSTPWGGTSGATDTQYFGXG', 'CASSLAPGATSEKLFFGXG', 'CASSLAPGTTNEKLFFGXG', 'CASSLGGGGFYEQYFGXG', 'CASSLSPTSGLSYEQYFGXG', 'CASSALGGGGTGELFFGXG']  
ebv_beta=['CASSPSGANVLTFGXG', 'CASSSLDTEAFFGXG', 'CASSSLSTEAFFGXG', 'CASSSPNTEAFFGXG', 'CSAPSLLNTEAFFGXG', 'CSARSEVGNTIYFGXG', 'CSVPSLLNTEAFFGXG', 'CACSSLNTEAFFGXG', 'CAGSSLNTEAFFGXG', 'CASSLDGRQVNQPQHFGXG', 'CASSLIPGDYYGYTFGXG', 'CASSLLTGHEQFFGXG', 'CASSPRTLGTEAFFGXG', 'CASSTGQAYEQYFGXG', 'CASSTRGGWVEAFFGXG', 'CSAGQGEGEQYFGXG', 'CSAHRTENTEAFFGXG', 'CSARDRTGNTIYFGXG', 'CSARDSTGKGYTFGXG', 'CSARGGTGNGYTFGXG', 'CSARSEVGDTIYFGXG', 'CSARSGVGNTIYFGXG', 'CSARVEPGNGYTFGXG', 'CSATDSMNTEAFFGXG', 'CSGGQGEGEQFFGXG', 'CSGGQGGGEQFFGXG', 'CSSGTGDGGEQFFGXG', 'CSTGQGPYEQYFGXG', 'CSTGSGEGYEQYFGXG', 'CSVDLANAEAFFGXG', 'CSVDLANTEAFFGXG', 'CSVETGDEKLFFGXG', 'CSVGAGEGGPQHFGXG', 'CSVGGGTEAFFGXG', 'CSVGGTFYGYTFGXG', 'CSVGPGENGPQHFGXG', 'CSVGQGEDGPQHFGXG', 'CSVGQGGNYGYTFGXG', 'CSVGQGGTNEKLFFGXG', 'CSVGSGGTNERLFFGXG', 'CSVGTGDNSPLHFGXG', 'CSVKGQGTEAFFGXG', 'CSVKGTNTEAFFGXG', 'CSVPGQVLETQYFGXG', 'CSVPGTDYNEQFFGXG', 'CSVQEGGYGYTFGXG', 'CSVTAGEDQPQHFGXG', 'CSVTSERTGTNWGYTFGXG', 'CSVTSERTGTTWGYTFGXG', 'CSYSPGQGRNEQFFGXG', 'CSARDGTGNGYTFGXG', 'CSARDRTGNGYTFGXG', 'CSARDRVGNTIYFGXG', 'CASSSLNTEAFFGXG', 'CSGGQGEGEQYFGXG', 'CASSDTGGNQPQHFGXG', 'CAISATGAVTEAFFGXG', 'CATLAGEGEQFFGXG', 'CASSFGGGSNYGYTFGXG', 'CASSFTWTSGETTDTQYFGXG', 'CASSHVINQFFGXG', 'CASSLASSGYTGELFFGXG', 'CASSLGTGHNEQFFGXG', 'CASSPITRIVGDTQYFGXG', 'CASSSGNTEAFFGXG', 'CASSSPGDYTYEQYFGXG', 'CASSWGAGSNYGYTFGXG', 'CASSWGGGSNYGYTFGXG', 'CASTPGTEYNEQYFFGXG', 'CASLFTGTSPTDTQYFGXG', 'CASSFSGSLTTEAFFGXG', 'CASSLGDRGLGYTFGXG', 'CASSLGTSFRTDTQYFGXG', 'CASSLIGGDYEQYFGXG', 'CASSLLGEKAYEQYFGXG', 'CASSLVGGQETQYFGXG', 'CASSPGTSGGGDEETQYFGXG', 'CASSSMVAGEYEQFFGXG', 'CASLYRSSTDTQYFGXG', 'CASSFPTSPPITQYFGXG', 'CASSPTGTSHTGELFFGXG', 'CATLISQGSRAGELFFGXG', 'CASTGGSGYTFGXG', 'CASSGTHNEQFFGXG', 'CASSQSPGGIQYFGXG', 'CASSQVSGQGALRALEQFFGXG', 'CATSTGLAGNHEQYFGXG', 'CATTQYGTDTQYFGXG', 'CASKMRGDVYEQYFGXG', 'CASLASGQGSHEQFFGXG', 'CASSPDGELFFGXG', 'CASSPFQRSSGNTIYFGXG', 'CASSPPGPTGRGWYDTFGXG', 'CASMGGASYNEQFFGXG', 'CASRGFLGGGQPQHFGXG', 'CASRGLLGGITEAFFGXG', 'CASSIDGTAYEQYFGXG', 'CASSIQDSLYNEQFFGXG', 'CASSIVGAHTEAFFGXG', 'CASSMLLGGGQPQHFGXG', 'CASTALLGGGYGYTFGXG', 'CATSQGSYGYTFGXG', 'CAGGTGETSPGELFGXG', 'CASRGMTPPTQYFGXG', 'CASSASAGGYYNEQFFGXG', 'CASSDGKIAPSEQYFGXG', 'CASSDSQRMNTEAFFGXG', 'CASSEAAGGFYNEQFFGXG', 'CASSLRTLDGYTFGXG', 'CASTPGSKLPDTQYFGXG', 'CASSLLGGGYAYEQYFGXG', 'CASSPSAAAYEQYFGXG', 'CSAGTGEGGEQFFGXG', 'CSVEASEGLFNEQFFGXG', 'CSVEASGGLFNEQFFGXG', 'CSVEYSPTLYNEQFFGXG', 'CSVGGVSSGVYNEQFFGXG', 'CSVGSGEDNEQFFGXG', 'CSVKGGFPYNEQFFGXG', 'CSVTAGEDDTQYFGXG', 'CSVGAGDYEQYFGXG', 'CSVGAGEGYEQYFGXG', 'CSVGFGEGYEQYFGXG', 'CSAEIIAEAIYNEQFFGXG', 'CSAGQALYNEQFFGXG', 'CSANTGGTYEQYFGXG', 'CSAPEVRGVWGYTFGXG', 'CSAPIPPYNEQFFGXG', 'CSARDCLGLAYEQYFGXG', 'CSARDGARGNTIYFGXG', 'CSARDGLGLAYEQYFGXG', 'CSARDQTGNGYTFGXG', 'CSARDRVGNGYTFGXG', 'CSAREIGGRHQPQHFGXG', 'CSARGAGFSGANVLTFGXG', 'CSARGEAITEKLFGXG', 'CSARGEGGSYNEQFFGXG', 'CSARQEGGSYNEQFFGXG', 'CSARSETGNTIYFGXG', 'CSASNQESYGYTFGXG', 'CSASPPSYNEQFFGXG', 'CSASRALDQPQHFGXG', 'CASSKEESSYNSPLHFGXG', 'CATATGTGSNTEAFFGXG', 'CATSDPDSPTDTQYFGXG', 'CATSDPTLAAYEQYFGXG', 'CATSDTGSFTDTQYFGXG', 'CASSARDRGIGGYTFGXG', 'CASSEGEGQGHYGYTFGXG', 'CASSLEGSYEQYFGXG', 'CASQRDYTGELFFGXG', 'CASRPLMGGASEAFFGXG', 'CASRTLLGGASEQYFGXG', 'CASSDLNSPLHFGXG', 'CASSFSPTAQGLEQYFGXG', 'CASSLSQGIQNIQYFGXG', 'CASSPGQPGPVRETQYFGXG', 'CASSPLTDTQYFGXG', 'CASSPTGLGGGYTFGXG', 'CAGPQGRETQYFGXG', 'CAGRPRLRGGNNEQFFGXG', 'CASSELTGGPYEQYFGXG', 'CASSFFLPTQREYEQYFGXG', 'CASSFIGLNTEAFFGXG', 'CASSFLAGGPPADTQYFGXG', 'CASSFQGSNEKLFFGXG', 'CASSLRNGYEQYFGXG', 'CASSLRTTNEKLFFGXG', 'CASSLSSATGELFFGXG', 'CASSLTSAAGELFFGXG', 'CASSLTSATGELFFGXG', 'CASSLWGEGLTPEAFFGXG', 'CASSLYSDTQYFGXG', 'CASSPLPGTTGTDTQYFGXG', 'CASSRTSATGELFFGXG', 'CASSSLRGSNQPQHFGXG', 'CASSSLTGSGQPQHFGXG', 'CASSSSLGFGELFFGXG', 'CASTQTSAAGELFFGXG', 'CASYWGLAVNEQFFGXG', 'CSVGSGGTNEKLFFGXG', 'CSVQEGNYGYTFGXG', 'CSDGTGDFGTQYFGXG', 'CSTGTGEGGTQYFGXG', 'CSVEEVEAFFGXG', 'CSVEGGPGTAYNEQFFGXG', 'CSVEVQRETEQFFGXG', 'CSVGADGTNEKLFFGXG', 'CSVGGAYEQYFGXG', 'CSVGSQGTNEKLFFGXG', 'CSVGTGGTNEKLFFGXG', 'CSVSAGEEDTQYFGXG', 'CSVSTGGTNEKLFFGXG', 'CSVVLAPVQEQFFGXG', 'CASSPGTLYGYTFGXG', 'CASSPSLVGSADTQYFGXG', 'CASSPTSGSIYEQYFGXG', 'CASSQAGQGNSPLHFGXG', 'CASSQDPRRSYNEQFFGXG', 'CASSQEGRVVGGEQFFGXG', 'CASSQGPGQEHYGYTFGXG', 'CASSQTLAGGGETQYFGXG', 'CASSQTTSVNTEAFFGXG', 'CASSQVRGGYEQFFGXG', 'CASSQVRGRGEQYFGXG', 'CASNPGTSNEQFFGXG', 'CASSLETGSYEQYFGXG', 'CASSPGQGSSYEQYFGXG', 'CASSQAGATRTDTQYFGXG', 'CASSQAGGTMNTEAFFGXG', 'CASSQDAGYEAFFGXG', 'CASSQDRLTGGYTFGXG', 'CASSQEGFREQFFGXG', 'CASSQETGASGTQYFGXG', 'CASSQETGSASQHFGXG', 'CASSQETGSYEQFFGXG', 'CASSQETGSYEQYFGXG', 'CASSQETSLYNEQFFGXG', 'CASSQGALTGQPQHFGXG', 'CASSQGFGGGETQYFGXG', 'CASSQGVGENTEAFFGXG', 'CASSPGQVTPLHFGXG', 'CASSPGVTSGRMGEQYFGXG', 'CASSPLIGTSGTEAFFGXG', 'CASSQAQGMGNSPLHFGXG', 'CASSQDQASEGSETQYFGXG', 'CASSQGVLLNEQFFGXG', 'CASSQVQGTSGGEQYFGXG', 'CASRAGLAEVSYEQYFGXG', 'CASSFRLAVKNEQFFGXG', 'CASSFRDRGSSGGIKGEKLFFGXG', 'CASSPASSGSWETQYFGXG', 'CASSSNRDRNTIYFGXG', 'CASSEEDGQAYEQYFGXG', 'CATSWTGTYEQYFGXG', 'CASSLFGERNEQYFGXG', 'CASSLQGSNQPQHFGXG', 'CASSQEGTGSYEQYFGXG', 'CASSYMGVEQFFGXG', 'CASTPMGLSSGETQYFGXG', 'CASTSGFGSGETQYFGXG', 'CASTVQGRETQYFGXG', 'CASREGSGDNNEQFFGXG', 'CASSDSSLTEAFFGXG', 'CASSESLAVHEQFFGXG', 'CASSAAGELETQYFGXG', 'CASSRRSQGLNTEAFFGXG', 'CASRYRDDSYNEQFFGXG', 'CASRTLAGPNTGELFFGXG', 'CASSLLGHPSGELFFGXG', 'CASSLNGGHYEQYFGXG', 'CASSLNRGAREKLFFGXG', 'CASSLTGGTYEQYFGXG', 'CASSLVLSSPTYYEQYFGXG', 'CASSLVVIQETQYFGXG', 'CASSQGSGATNEQFFGXG', 'CASSQGSGATNGQFFGXG', 'CASSQIVTSAAQYFGXG', 'CASSVLAGDTQYFGXG', 'CASSWGQGSNYGYTFGXG', 'CASSLIASGGYNEQFFGXG', 'CASSLTLLGNNEQYFGXG', 'CASSRGTGEGYEQYFGXG', 'CASSLAVLSSYNEQFFGXG', 'CASSLEAGVSYEQYFGXG', 'CASSLGRGRGNEQFFGXG', 'CASSLLIGANNEQFFGXG', 'CASTREGLNTGELFGXG', 'CASIPEGGRETQYFGXG', 'CASSIGQAYEQYFGXG', 'CASSLGLENEQFGXG', 'CASSLGQAYEQYFGXG', 'CASSMLGGGRDEQFFGXG', 'CASSPGTGEGYEQYFGXG', 'CASSPTNPAGDTETQYFGXG', 'CASSRFFPGQGDHAKNIQYFGXG', 'CASSSGQAYEQYFGXG', 'CASSSVNEQYFGXG', 'CASSVGQAYELYFGXG', 'CASSVGQAYEQYFGXG', 'CASGWGSQPQHFGXG', 'CASLRGLGTDTQYFGXG', 'CASSEPGQGGRGEQYFGXG', 'CASSHIRDYGAFFGXG', 'CASSKQGRGTDTQYFGXG', 'CASSLAPSYEQYFGXG', 'CASSLGASTDTQYFGXG', 'CASSLGLGVNNEQFFGXG', 'CASSLGVSQETQYFGXG', 'CASSLNTLSTEAFFGXG', 'CASSLPGTSGISQDTQYFGXG', 'CASSLPRGRDNEQFFGXG', 'CASSLSSPGNQPQHFGXG', 'CASSLTAPGIQPQHPFGXG', 'CASSLTEAGNQPHHFGXG', 'CASSLTGAGDQPQHFGXG', 'CASSLTGPGDQPQHFGXG', 'CASSLVSSGANVLTFGXG', 'CASSPLGHRDTEAFFGXG', 'CASSRTDDTEAFFGXG', 'CASSSARGHHTQYFGXG', 'CASSSLGGVDQPQHFGXG', 'CASSSTEQATYGYTFGXG', 'CASSSTGPGNSPLHFGXG', 'CASSSVGPGDQPQHFGXG', 'CASSYLGDSTNSPLHFGXG', 'CASTGWVTDTQYFGXG', 'CASSPSKPGDNEQFFGXG', 'CASGTGQLTNTEAFFGXG', 'CASREGDINTGELFFGXG', 'CASSAASGTDTQYFGXG', 'CASSARGGADEQFFGXG', 'CASSEILGMNTEAFFGXG', 'CASSTGQLTNTEAFFGXG', 'CASSVASGTDTQYFGXG', 'CASSVELGSGRETQYFGXG', 'CASTELGDTHNEQFFGXG', 'CASSFGQQETQYFGXG', 'CASSPLAGKGEPQHFGXG', 'CASSAWLVETQYFGXG', 'CASSEGRVAPGELFFGXG', 'CASSEGRVLPGELFFGXG', 'CASSEGRVSPGELFFGXG', 'CSAEPGTQGGTQYFGXG', 'CSARDGTGNDYTFGXG', 'CSARDNLSGYTFGXG', 'CSARDQTGNDYTFGXG', 'CSARDRSLGNTIYFGXG', 'CSAREGTGNGYTFGXG', 'CSARGQGRDAAFFGXG', 'CSARIGVGNAIYFGXG', 'CSARIGVGNTIYFGXG', 'CSARVGVGNTIYFGXG', 'CASSTSDTQYFGXG', 'CSATVTGGWNEQFFGXG', 'CSSQEGGYGYTFGXG', 'CSTQEGGYGYTFGXG', 'CSVEDQRKTKNIQYFGXG', 'CSVPFEGGTLETQHFGXG', 'CSVPFEGGTLETQYFGXG', 'CASSQDRQGQIYGYTFGXG', 'CASSHVGGYEQYFGXG', 'CASSFSRDSDEQFFGXG', 'CASSFSRNSDEQFFGXG', 'CASSLDLGTAKYGYTFGXG', 'CASSLGNTEAFFGXG', 'CASSQEEANYGYTFGXG', 'CASTPDGDNEQFFGXG', 'CASSVAGGDEQYFGXG']
# this drops the GXG motif
for idx,seq in enumerate(cmv_beta):
    cmv_beta[idx]=seq[:-3]
for idx,seq in enumerate(ebv_beta):
    ebv_beta[idx]=seq[:-3]


seqs[0]=dp.filtr(seqs[0], 13)
seqs[1]=dp.filtr(seqs[1], 13)


#==============================================================================
# Intersection between two sets
#==============================================================================

cmv_beta=set(cmv_beta)
ebv_beta=set(ebv_beta)
print('CMV in CD4s:')
print(len(cmv_beta.intersection(seqs[0])))

print('CMV in CD8s:')
print(len(cmv_beta.intersection(seqs[1])))

print('EBV in CD4s:')
print(len(ebv_beta.intersection(seqs[0])))

print('EBV in CD8s:')
print(len(ebv_beta.intersection(seqs[1])))

# these are the sequences that are present
ebv_beta=list(ebv_beta.intersection(seqs[1]))+list(ebv_beta.intersection(seqs[0]))
cmv_beta=list(cmv_beta.intersection(seqs[1]))+list(cmv_beta.intersection(seqs[0]))

# the most common for ebv is 13
# the most common for cmv 16/13

#==============================================================================
# Filter original seqs to 13 and build the dict
#==============================================================================

seqs[0]=dp.filtr(seqs[0], 13)
seqs[1]=dp.filtr(seqs[1], 13)

newCD4=dp.seq2fatch(seqs[0].copy())
newCD8=dp.seq2fatch(seqs[1].copy())

cmv_work=dp.seq2fatch(cmv_beta.copy())
ebv_work=dp.seq2fatch(ebv_beta.copy())

# use function to create data
X, y = dp.dataCreator(newCD4,newCD8)

X=X[:10000]
y=y[:10000]

y=np.concatenate((y,np.zeros((len(ebv_work))),np.zeros((len(cmv_work)))),0)
X=np.concatenate((X,ebv_work,cmv_work),0)

pdb.set_trace()

newCD4=None
newCD8=None

print("Running tSNE")       
tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000, verbose=1)
two_d_embeddings_1 = tsne.fit_transform(X)

def plot(embeddings, labels, seqs):
    assert embeddings.shape[0] >= len(labels), 'More labels than embeddings'
    pylab.figure(figsize=(100,100))  # in inches
    for i, label in enumerate(labels):
        x, y = embeddings[i,:]
        if seqs[i] in ebv_beta:
            print('ping')
            pylab.scatter(x, y, c='r') # ebv is red
        elif seqs[i] in cmv_beta:
            print('ping')
            pylab.scatter(x, y, c='y') # cmv is yellow
        else:
            pylab.scatter(x, y, c='b')
        # comment in for labels as the seqs to be added
        #pylab.annotate(seqs[i], xy=(x, y), xytext=(5, 2), textcoords='offset points',  ha='right', va='bottom')
    pylab.title("t-SNE 2-D Embeddings of 13 Long Sequences with highlighted EBV/CMV")
    pylab.show()
    return
    
# comment in to produce the maaaaasive plot  
plot(two_d_embeddings_1, y, seqs[0]+seqs[1])

# plot using seaborn to get a heatmap, looks pretty in two different graphs
